package com.teljjb.dao;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.teljjb.bean.PlanSchedule;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface PlanScheduleDao {

	public PlanSchedule findPlanScheduleById(Integer id);
	
	public Integer insert(PlanSchedule param);
	
	public Integer getPlanScheduleCount(PlanSchedule param);
	
	public List<PlanSchedule> findPlanSchedulesByPage(@Param("param")PlanSchedule param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deletePlanScheduleById(Integer id);
}