package com.teljjb.dao;

import com.teljjb.bean.UserSignInRecord;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
@Repository
public interface UserSignInRecordDao {

	public UserSignInRecord findUserSignInRecordById(Integer id);
	
	public Integer insert(UserSignInRecord param);
	
	public Integer getUserSignInRecordCount(UserSignInRecord param);
	
	public List<UserSignInRecord> findUserSignInRecordsByPage(@Param("param") UserSignInRecord param, @Param("offset") Integer offset, @Param("rows") Integer rows);
	
	//if not use,pls delete it
	public Integer deleteUserSignInRecordById(Integer id);

    UserSignInRecord findUserSignInRecordByTime(Date date);
}